### PR TITLE
BUG: Use explicit unsigned type for compression stream interpretation

### PR DESCRIPTION
**Pull request by tbirdso**
Explicitly use signed 32-bit integer type for reinterpreting a bit
stream as a byte stream before writing to disk.

Resolves error previously occurring in cases where built-in
`int.to_bytes` attempted to interpret signed integer as unsigned by
default. This error prevented some samples from being compressed.

```
...
File "neuroglancer_formatting_scripts\src\neuroglancer_interface\compression\utils.py", line 252, in bits_to_bytes
    byte_stream[i_val*4:(i_val+1)*4] = int(val).to_bytes(4, byteorder='little')
OverflowError: can't convert negative int to unsigned
```

Refer to `int.to_bytes` documentation:
https://docs.python.org/3/library/stdtypes.html

Also adds `.gitignore` file to keep autogenerated `__pycache__` files out of Git history.

### CODE REVIEW

**Comment by danielsf** [comment]
@tbirdso Do you know how a negative value was getting to that line in the code?

Given that this code is meant to compress the segmentation volume, I would expect all of the input values to be positive definite. Are you trying to process volumes with labels that are < 0?

**Comment by danielsf** [comment]
Specifically, I'm wondering if we need to add a validation check at the top of this function

https://github.com/AllenInstitute/neuroglancer_formatting_scripts/blob/main/src/neuroglancer_interface/compression/utils.py#L8

to make sure that `0 <= data < 2**32`

**Comment by tbirdso** [comment]
Hi @danielsf , I observed the `OverflowError` when trying to convert the 25um CCF v3.1 atlas from NIFTI format to neuroglancer precomputed format with compression.

The input file `annotation_25.nii.gz` is available here: http://download.alleninstitute.org/informatics-archive/converted_mouse_ccf/annotation/ccf_2017/

When I inspect the atlas with ITK it appears that the image has type `unsigned int` and is on the range `[0, 614454277]` which is indeed within `0 <= data < 2**32`:
```py
>>> import itk
>>> import numpy as np
>>> image = itk.imread('annotation_25.nii.gz')
>>> np.min(image)
0
>>> np.max(image)
614454277
>>> type(image)
<class 'itk.itkImagePython.itkImageUI3'>
```

Under the status quo a negative value is found in the `values` numpy array when `bit_grid` is interpreted as a stream of 32-bit _signed_ integers. Tracing with `pdb`:
```py
> c:\repos\neuroglancer_formatting_scripts\src\neuroglancer_interface\compression\utils.py(257)bits_to_bytes()
-> raise e
(Pdb) p i_val
7806
(Pdb) p val
-65536
(Pdb) np.min(values)
-67108864
(Pdb) np.max(values)
16777215
(Pdb) w
  <stdin>(1)<module>()
  c:\repos\neuroglancer_formatting_scripts\src\neuroglancer_interface\modules\ccf_multiscale_annotations.py(64)write_out_ccf()
-> do_chunking(metadata=scale_metadata,
  c:\repos\neuroglancer_formatting_scripts\src\neuroglancer_interface\modules\ccf_multiscale_annotations.py(144)do_chunking()
-> compress_ccf_data(
  c:\repos\neuroglancer_formatting_scripts\src\neuroglancer_interface\compression\utils.py(44)compress_ccf_data()
-> encoding_list.append(encode_block(block))
  c:\repos\neuroglancer_formatting_scripts\src\neuroglancer_interface\compression\utils.py(170)encode_block()
-> byte_stream = bits_to_bytes(bit_stream)
> c:\repos\neuroglancer_formatting_scripts\src\neuroglancer_interface\compression\utils.py(257)bits_to_bytes()
-> raise e
```

When the bit stream is converted using an unsigned rather than signed array the corresponding value is greater than any intensity observed in the image:
```
>>> values_unsigned[i_val]
4294901760
```

From a generic compression standpoint it generally makes sense to represent everything as unsigned to avoid unintended two's complement conversion. If it is expected that each set of 32 bits in the bit stream maps directly to an intensity value then it seems that something is not arranged as expected. Perhaps relevant to endianness?

**Comment by danielsf** [comment]
I see. I was just concerned because I'd never stumbled over this problem before. Apparently, the data that I was running on a much smaller sample of label values, so it never got close to the 2**32 limit.

**Review by danielsf — APPROVED** [review]

**Comment by danielsf** [comment]
Thanks for fixing this.

**Pull request merged**
